### ISSUE TITLE
Doesn't print Event Title

### ISSUE THREAD

**Issue by idevelopr** [sedouard/eventful-node#3]
```
for(var i in data.search.events){

    console.log(data.search.events[i].title);

  }
```

**Comment by sedouard** [comment]
Hey @idevelopr looks like eventful changed their api such that the `data.search.events` property is no longer an array but a dictionary. To get to the even listing looks like its now:

`data.search.events.event`

**Comment by idevelopr** [comment]
@sedouard It prints the entire data. How do I access specific details like **title** ?
